### ISSUE TITLE
Please explain the difference with AccurAssess

### ISSUE THREAD

**Issue by pcav** [jkibele/acc-assess#4]
see http://plugins.qgis.org/plugins/AccurAssess/
please add to metadata, so the user will be aware of this

**Comment by jkibele** [comment]
Some of my code was used to make that other plugin but I don't know the authors and haven't really used their plugin. I don't really know what it does. I looked into it a bit when I first noticed that it was available but I can't remember.

This is an inherent issue with QGIS plugins and user contributed software in general. As a user it's often difficult to know what is available and how to distinguish between different options that do similar things. I don't expect plugin authors to provide and maintain a list of similar plugins. The best we can do is try to provide a clear explanation of what our plugin does (like [this](https://github.com/jkibele/acc-assess/blob/master/README.md)).

**Comment by pcav** [comment]
Thanks Jared.
